#################
### AUTOSTART ###
#################

exec-once = [workspace 1 silent] $terminal
exec-once = [workspace 11 silent] $terminal -e btop
exec-once = [workspace 11 silent] $terminal -e nload -i 100000 -o 40000
exec-once = pidof fcitx5 || fcitx5
exec-once = waybar
exec-once = hypridle
exec-once = hyprpaper
exec-once = hyprsunset
