##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = ignore-maximize-requests
  suppress_event = maximize
  match:class = .*
}

# Fix some dragging issues with XWayland
windowrule {
  name = fix-xwayland-dragging
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

# Make xwayland window border different color
windowrule {
  name = xwayland-red-borders
  border_color = rgba(ff0066ee)
  match:xwayland = 1
}
