# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

# See https://wiki.hypr.land/Configuring/Keywords/
# Set programs that you use
$terminal = alacritty
$menu = rofi -show run -show-icons -theme onedark

source = ~/.config/hypr/land/*.conf
