general {
    # lock_cmd = pgrep -u "$(id -u)" -x hyprlock > /dev/null || hyprlock
    lock_cmd = pgrep -u "$(id -u)" -x swaylock > /dev/null || swaylock --color 333333 --show-failed-attempts
}

listener {
    timeout = 10
    # on-timeout = pgrep -u "$(id -u)" -x hyprlock > /dev/null && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-timeout = pgrep -u "$(id -u)" -x swaylock > /dev/null && hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 305
    # on-timeout = pgrep -u "$(id -u)" -x hyprlock > /dev/null || hyprlock --grace 5
    on-timeout = pgrep -u "$(id -u)" -x swaylock > /dev/null || swaylock --color 333333 --show-failed-attempts
}

listener {
    timeout = 310
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
